kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: i+BAKTZrMa48Xw22ervkIt9ZNgcbeI8mTyl1mvH3RPY=
      - identity: {}
