---
version: '3.3'

services:
  mongo_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - posts_db:/data/db
    networks:
      net_backend:
        aliases:
          - post_db
          - comment_db

  ui:
    #build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${PUBLIC_HTTP_PORT}:9292/tcp
    networks:
      - net_frontend

  post:
    #build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - net_frontend
      - net_backend

  comment:
    #build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - net_frontend
      - net_backend

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    networks:
      - net_frontend
      - net_backend
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

volumes:
  posts_db:
  prometheus_data:

networks:
  net_frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24

  net_backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.2.0/24
