---
version: '3.3'

services:
# Application
  mongo_db:
    image: mongo:${MONGO_VERSION:-latest}
    volumes:
      - posts_db:/data/db
    networks:
      net_backend:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USERNAME}/ui:${UI_VERSION:-latest}
    ports:
      - ${PUBLIC_HTTP_PORT}:9292/tcp
    networks:
      - net_frontend

  post:
    image: ${USERNAME}/post:${POST_VERSION:-latest}
    networks:
      - net_frontend
      - net_backend

  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION:-latest}
    networks:
      - net_frontend
      - net_backend
  
volumes:
  posts_db:

networks:
  net_frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24

  net_backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.2.0/24
