groups:
  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'
    
    - alert: HTTPSlowResponse
      expr: histogram_quantile(0.95, sum(rate(ui_request_latency_seconds_bucket[5m])) by (le)) > 0.03
      for: 1m
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has long response time'
        summary: 'HTTP response time of {{ $labels.instance }} is long!'
