---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mongo_db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo_db
  template:
    metadata:
      name: mongo_db
      labels:
        app: mongo_db
    spec:
      containers:
      - image: mongo
        name: mongo_db
